apiVersion: v1
kind: Service
metadata:
  name: app01
spec:
  ports:
  - port: 22
    protocol: TCP
  selector:
    name: app01
---
apiVersion: v1
kind: Pod
metadata:
  name: app01
  labels:
    name: app01
spec:
  containers:
  - image: rastasheep/ubuntu-sshd:16.04
    volumeMounts:
    - name: ssh-key-pub-volume
      mountPath: "/etc/ssh-key"
    name: sshd
  volumes:
  - name: ssh-key-pub-volume
    secret:
      secretName: ssh-key-pub-secret
      defaultMode: 256
