apiVersion: v1
kind: Service
metadata:
  name: app02
spec:
  ports:
  - port: 22
    name: ssh
    protocol: TCP
  - port: 80
    name: tcp-80
    protocol: TCP
  selector:
    name: app02
---
apiVersion: v1
kind: Pod
metadata:
  name: app02
  labels:
    name: app02
spec:
  containers:
  - name: sshd
    image: ansible:ubuntu1404
    imagePullPolicy: Never
