apiVersion: v1
kind: Service
metadata:
  name: control
  labels:
    name: control
spec:
  selector:
    name: control
  ports:
    - port: 22
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: control
  labels:
    name: control
spec:
  containers:
  - name: control
    image: ansible:ubuntu1404
    imagePullPolicy: Never
    command:
      - sleep
      - "3600"
    workingDir: "/src/ansible"
    volumeMounts:
    - name: host-mount
      mountPath: "/src/ansible"
  volumes:
  - name: host-mount
    hostPath:
      path: "/src/ansible/"
