apiVersion: v1
kind: Service
metadata:
  name: control
  labels:
    name: control
spec:
  selector:
    name: control
  ports:
    - port: 22
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: control
  labels:
    name: control
spec:
  containers:
  - image: williamyeh/ansible:ubuntu16.04
    command:
      - sleep
      - "3600"
    name: control
    workingDir: "/src/ansible"
    volumeMounts:
    - name: host-mount
      mountPath: "/src/ansible"
    - name: ssh-key-volume
      mountPath: "/etc/ssh-key"
  volumes:
  - name: host-mount
    hostPath:
      path: "/src/ansible/"
  - name: ssh-key-volume
    secret:
      secretName: ssh-key-secret
      defaultMode: 256
