apiVersion: v1
kind: Service
metadata:
  name: db01
spec:
  ports:
  - port: 22
    protocol: TCP
  selector:
    name: db01
---
apiVersion: v1
kind: Pod
metadata:
  name: db01
  labels:
    name: db01
spec:
  containers:
  - name: sshd
    image: ansible:ubuntu1404
    imagePullPolicy: Never
