apiVersion: v1
kind: Service
metadata:
  name: lb01
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
  - name: tcp-80
    port: 80
    protocol: TCP
  selector:
    name: lb01
---
apiVersion: v1
kind: Pod
metadata:
  name: lb01
  labels:
    name: lb01
spec:
  containers:
  - name: sshd
    image: ansible:ubuntu1404
    imagePullPolicy: Never
